build-LambdaFunction:
	webpack
	cp ./build/app.js ${ARTIFACTS_DIR}/app.js
    # cp *.js artifact
    # cp package.json artifact
	# cp package-lock.json artifact
    # npm install --production -t artifact

